mkdir -p blaze_hailo/build

g++ -DHAILO_SDK_AVAILABLE -I. -I/usr/include/opencv4 -I/usr/include/hailo -I/opt/hailo/include -I./blaze_common -I./blaze_hailo -I.. -c blaze_common/Config.cpp -o blaze_hailo/build/Config.o
g++ -DHAILO_SDK_AVAILABLE -I. -I/usr/include/opencv4 -I/usr/include/hailo -I/opt/hailo/include -I./blaze_common -I./blaze_hailo -I.. -c blaze_common/Base.cpp -o blaze_hailo/build/Base.o

g++ -std=c++17 -Wall -Wextra -O3 -DNDEBUG -DHAILO_SDK_AVAILABLE -I/usr/include/opencv4  -I/usr/include/hailo -I/opt/hailo/include -I./blaze_common -I./blaze_hailo -I.. -fPIC -c blaze_common/visualization.cpp -o blaze_hailo/build/visualization.o

g++ -DHAILO_SDK_AVAILABLE -I. -I/usr/include/opencv4 -I/usr/include/hailo -I/opt/hailo/include -I./blaze_common -I./blaze_hailo -I.. -c blaze_hailo/HailoInference.cpp -o blaze_hailo/build/HailoInference.o

g++ -DHAILO_SDK_AVAILABLE -I. -I/usr/include/opencv4 -I/usr/include/hailo -I/opt/hailo/include -I./blaze_common -I./blaze_hailo -I.. -c blaze_hailo/Detector.cpp -o blaze_hailo/build/Detector.o
g++ -DHAILO_SDK_AVAILABLE -I. -I/usr/include/opencv4 -I/usr/include/hailo -I/opt/hailo/include -I./blaze_common -I./blaze_hailo -I.. -c blaze_hailo/Landmark.cpp -o blaze_hailo/build/Landmark.o

#g++ -std=c++17 -Wall -Wextra -O3 -DNDEBUG -DHAILO_SDK_AVAILABLE -I/usr/include/opencv4  -I/usr/include/hailo -I/opt/hailo/include -I./blaze_common -I./blaze_hailo -I.. -c -o blaze_detect_live_hailo.o blaze_detect_live_hailo.cpp

#g++ -o blaze_detect_live_hailo blaze_detect_live_hailo.o blaze_hailo/build/Config.o blaze_hailo/build/Base.o blaze_hailo/build/visualization.o blaze_hailo/build/HailoInference.o blaze_hailo/build/Detector.o blaze_hailo/build/Landmark.o -L. -Wl,-rpath,. -lopencv_stitching -lopencv_alphamat -lopencv_aruco -lopencv_barcode -lopencv_bgsegm -lopencv_bioinspired -lopencv_ccalib -lopencv_cvv -lopencv_dnn_objdetect -lopencv_dnn_superres -lopencv_dpm -lopencv_face -lopencv_freetype -lopencv_fuzzy -lopencv_hdf -lopencv_hfs -lopencv_img_hash -lopencv_intensity_transform -lopencv_line_descriptor -lopencv_mcc -lopencv_quality -lopencv_rapid -lopencv_reg -lopencv_rgbd -lopencv_saliency -lopencv_shape -lopencv_stereo -lopencv_structured_light -lopencv_phase_unwrapping -lopencv_superres -lopencv_optflow -lopencv_surface_matching -lopencv_tracking -lopencv_highgui -lopencv_datasets -lopencv_text -lopencv_plot -lopencv_ml -lopencv_videostab -lopencv_videoio -lopencv_viz -lopencv_wechat_qrcode -lopencv_ximgproc -lopencv_video -lopencv_xobjdetect -lopencv_objdetect -lopencv_calib3d -lopencv_imgcodecs -lopencv_features2d -lopencv_dnn -lopencv_flann -lopencv_xphoto -lopencv_photo -lopencv_imgproc -lopencv_core  -lhailort -lpthread

g++ -std=c++17 -Wall -Wextra -O3 -DNDEBUG -DHAILO_SDK_AVAILABLE -I/usr/include/opencv4  -I/usr/include/hailo -I/opt/hailo/include -I./blaze_common -I./blaze_hailo -I.. -c -o blaze_hailo/build/blaze_detect_live.o blaze_hailo/blaze_detect_live.cpp

g++ -o blaze_hailo/blaze_detect_live blaze_hailo/build/blaze_detect_live.o blaze_hailo/build/Config.o blaze_hailo/build/Base.o blaze_hailo/build/visualization.o blaze_hailo/build/HailoInference.o blaze_hailo/build/Detector.o blaze_hailo/build/Landmark.o -L. -Wl,-rpath,. -lopencv_stitching -lopencv_alphamat -lopencv_aruco -lopencv_barcode -lopencv_bgsegm -lopencv_bioinspired -lopencv_ccalib -lopencv_cvv -lopencv_dnn_objdetect -lopencv_dnn_superres -lopencv_dpm -lopencv_face -lopencv_freetype -lopencv_fuzzy -lopencv_hdf -lopencv_hfs -lopencv_img_hash -lopencv_intensity_transform -lopencv_line_descriptor -lopencv_mcc -lopencv_quality -lopencv_rapid -lopencv_reg -lopencv_rgbd -lopencv_saliency -lopencv_shape -lopencv_stereo -lopencv_structured_light -lopencv_phase_unwrapping -lopencv_superres -lopencv_optflow -lopencv_surface_matching -lopencv_tracking -lopencv_highgui -lopencv_datasets -lopencv_text -lopencv_plot -lopencv_ml -lopencv_videostab -lopencv_videoio -lopencv_viz -lopencv_wechat_qrcode -lopencv_ximgproc -lopencv_video -lopencv_xobjdetect -lopencv_objdetect -lopencv_calib3d -lopencv_imgcodecs -lopencv_features2d -lopencv_dnn -lopencv_flann -lopencv_xphoto -lopencv_photo -lopencv_imgproc -lopencv_core  -lhailort -lpthread
